![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [ ]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print("POP")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [ ]:
# TESTANDO
S = Stack()

In [ ]:
S.print_stack()

In [ ]:
S.push(1)

In [ ]:
S.push(2)

In [ ]:
S.push(3)

In [ ]:
S.print_stack()

In [ ]:
S.pop()

In [ ]:
S.pop()

In [ ]:
S.print_stack()

In [ ]:
S.push(7)

In [ ]:
S.push(8)

In [ ]:
S.push(9)

In [ ]:
S.print_stack()

In [ ]:
print(S.is_empty())

### Segunda Implementação

In [1]:
import numpy as np

In [2]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            self.__valores[self.__topo] = 0
            self.__topo -= 1
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [3]:
pilha = Pilha(5)

In [4]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [5]:
pilha.ver_topo()

-1

In [6]:
pilha.empilhar(1)
pilha.ver_topo()

np.int64(1)

In [7]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [8]:
pilha.imprime_pilha()

[1 1 2 3 4]


In [9]:
pilha.empilhar(6)

A pilha está cheia


In [10]:
pilha.ver_topo()

np.int64(4)

In [11]:
pilha.desempilhar()

In [12]:
pilha.ver_topo()

np.int64(3)

In [19]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

A pilha está vazia
A pilha está vazia


In [20]:
pilha.ver_topo()

-1

In [14]:
pilha.imprime_pilha()

[1 1 2 3 0]


In [21]:
pilha.desempilhar()

A pilha está vazia


In [22]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [23]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [24]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [26]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  27


NameError: name 'Stack' is not defined

### Fim Teoria Aula 6